version: 0.2

phases:
  install:"
    runtime-versions:
     java:corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEAFAULT_REGION)
      -CONTAINER_NAME=auth
  build:
    commands:
      - echo Build started on `date`
      - echo $IMAGE_NAME
      -mvn clean package -Ddockerfile.skip
      -docker build -t $IMAGE_NAME         
  post_build:
    commands:
      -echo Build completed on 'date'
      -echo $(docker images)
      -docker tag $IMAGE_NAME $IMAGE_URI
      -echo Pushing docker image
      -docker push $IMAGE_URI
      -echo push completed
      -printf'[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinations.json
artifacts:
    files: taskdefinition.json1